IT-35944 / TargetSystemMappings added
apgsga-it/apg-jenkins-pipeline-libs pull request #1
Opened 2020-08-14 05:46 UTC by apgsga-jhe

@chhex : a quick one to be merged here. Basically what we discussed on Thursday (13.08), and using now GroovyShell in the test class. 
"resources" folder added in order for the pipeline to use the build-in functionality to load a resource.
resources/targetSystemMappings.groovy will be the file retrieve from Github by Piper (pull request on corresponfing project will follow)

2020-09-17 08:27 UTC, chhex commented
@apgsga-jhe  Not quite sure what the State of this pull request is? 
Some specific questions inline.

2020-09-17 08:29 UTC, apgsga-jhe commented
> @apgsga-jhe Not quite sure what the State of this pull request is?
> Some specific questions inline.

@chhex : this one has been merged since relativ long already. Which question do you mean?

2020-09-17 08:32 UTC, chhex requested changes
@apgsga-jhe  As a general comment: I think it is are the current stage - integration - that we finish our components - at least on a API level.  In Order to move on with the Integration.

2020-09-17 08:32 UTC, chhex commented on resources/targetSystemMappings.groovy
> +import groovy.json.JsonSlurper
@apgsga-jhe  Where is the TargetSystemMapping Json File?
I would expect it also here, in resources and not configurable.

2020-09-17 08:32 UTC, chhex commented on resources/targetSystemMappings.groovy
> +    def setTsmFile(def tsmFile){
@apgsga-jhe  Why configurable?  For testing purposes? 
But then i would certainly provide the correct default. 
For me the Groovy Api and the JSON File should totally tightly coupled

2020-09-17 08:45 UTC, apgsga-jhe commented
@chhex  : Sooorryy, I mixed up this pull request with another one .... effectively, this one has not been merged yet .... sure I'll have a look

2020-09-17 10:15 UTC, apgsga-jhe commented on resources/targetSystemMappings.groovy
> +    def setTsmFile(def tsmFile){
@chhex : Thinking twice about it .... This is naturally easier for unit-testing purpose, but not only. If we provide the JSON file from Github as well as part of the project, then, our test environment (typically our test-VM, or a future jenkins-t) will be configured with productive environment, I think this can be risky  .... I would keep the file separated, knowing that yeah, piper and pipelines will have to provide the path to it when needed. In Piper, this was already thought like that with https://github.com/apgsga-it/piper/blob/master/apg-patch-system-mapping/src/main/groovy/com/apgsga/system/mapping/impl/TargetSystemMappingImpl.groovy

2020-09-17 11:40 UTC, chhex commented on resources/targetSystemMappings.groovy
> +    def setTsmFile(def tsmFile){
@apgsga-jhe I get get your point.... but i think we are turning in circles ;-) 

Now we have as i see it a Api, a implementation , a Json Daten structure and a wrapper implementation , which loads the implementation from somewhere , which loads the data from somewhere else .... all in different places.  

Where to should the Json file be?  So the implementation load as file from somewhere ... where actually? And the location can be different for piper and for the pipelines ...... 

The whole point, was for me to centralize TargetSystemMapping and have the possibility to version it,  be it only with commit. 

For me quite clearly  the Wrapper Implementation should not need to know anything about where the File is.  For me  clearly the responsibility of the Implementation it self. 

I understand your reservations.... but those should be addressed in the implementation. 

Thinking of it you probably want to seperate the Creation of the Wrapper ... and the Implementation from the Implementation itself with a Factory or Builder.  

The Builder could be parameterized via Spring Profile and in the Pipeline

2020-09-17 18:43 UTC, chhex commented on resources/targetSystemMappings.groovy
> +    def setTsmFile(def tsmFile){
@apgsga-jhe Actually the Factory in piper could also be a wrapper around the pipeline Factory, doing the additional things like clone, loading the script etc , but then delegateing to the pipeline TargetSystemMapping Factory, where the Spring Profiles map to the Factory Variants , for Production, Integration Test and Unit Test..... possibly the Unit Test, taking the path to json file, possibly.....

2020-09-22 07:55 UTC, apgsga-jhe commented
@chhex  : This one can be rejected .... I mean, closed without merging it.

2020-09-22 08:54 UTC, closed without merging